POST http://localhost:4002/products
content-type: application/json

{
    "name" : "borracha",
    "price" : 1.99
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/

###

PUT  http://localhost:4002/products/
content-type: application/json

{
    "name" : "caderno 96 folhas preto",
    "price" : 10.99
}

###

DELETE http://localhost:4002/products/